import { Op } from 'sequelize';

const operatorsAliases = {
  _eq: Op.eq,
  _ne: Op.ne,
  _gte: Op.gte,
  _gt: Op.gt,
  _lte: Op.lte,
  _lt: Op.lt,
  _not: Op.not,
  _in: Op.in,
  _notIn: Op.notIn,
  _is: Op.is,
  _like: Op.like,
  _notLike: Op.notLike,
  _iLike: Op.iLike,
  _notILike: Op.notILike,
  _regexp: Op.regexp,
  _notRegexp: Op.notRegexp,
  _iRegexp: Op.iRegexp,
  _notIRegexp: Op.notIRegexp,
  _between: Op.between,
  _notBetween: Op.notBetween,
  _overlap: Op.overlap,
  _contains: Op.contains,
  _contained: Op.contained,
  _adjacent: Op.adjacent,
  _strictLeft: Op.strictLeft,
  _strictRight: Op.strictRight,
  _noExtendRight: Op.noExtendRight,
  _noExtendLeft: Op.noExtendLeft,
  _and: Op.and,
  _or: Op.or,
  _any: Op.any,
  _all: Op.all,
  _values: Op.values,
  _col: Op.col,
};

export default operatorsAliases;
